name: Build and create release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build standalone executable
        run: deno task compile

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Development release
          tag_name: dev
          make_latest: true
          files: ed-carrier-tracker-bot.exe